<?php

namespace Database\Seeders;

use App\Models\Lecturer;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LecturerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $lecturers = [
            [
                "name" => "Mustikasari, S.Kom., M.Kom.",
                "gender" => "female",
                "nip" => "19781106 200604 2 001",
                "signature" => "lecturer/signatures/head_signature.png",
                "role" => "head",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Hariani, S.Kom., M.Kom.",
                "gender" => "female",
                "nip" => null,
                "signature" => null,
                "role" => "secretary",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Dr. H. Kamaruddin Tone, M.M.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Nur Afif, S.T., M.T.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Faisal, S.T., M.T.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Faisal Akib, S.Kom., M.Kom.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Dr. Ridwan A. Kambau, S.T., M.Kom.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Antamil, S.T., M.T.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Firmansyah Ibrahim, S.Kom., M.Kom.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "A. Muhammad Syafar, S.T., M.T.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "A. Hutami Endang, S.Kom., M.Kom.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Sri Wahyuni, S.Kom., M.T.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Ir. A. Muhammad Syafar, S.T., M.T.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Ir. A. Muhammad Syafar, S.T., M.T., IPM.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Andi Muhammad Nur Hidayat, S.Kom., M.T.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Asep Indra Syahyadi, S.Kom., M.Kom.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Wahyuddin Saputra, S.Kom., M.T.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Muh. Nur Akbar, S.T., M.T.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Darmatasia, S.Pd., M.Kom.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "M. Hasrul H., M.Kom.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "M. Hasrul H., S.Kom., M.Kom.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Muhammad Nur Akbar, S.T., M.T.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Dr. Ridwan A. Kambau, S.T., M.Kom.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Faisal, S.T.,M.T.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Dr. H. Kamaruddin Tone, MM.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Faisal, S.T, M.T.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Faisal, S. T., M. T.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "A. Muhammad Syafar. S.T., M.T.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Wahyuddin Saputra, S.Kom., M.Kom.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Faisal Akib, S.Kom, M.Kom.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Antamil, S. T., M. T.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Dr. Ir. A. Muhammad Syafar, S.T., M.T., IPM.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Dr. H. Mukhlis Mukhtar, M.Ag.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Dr. Sohrah, M.Ag.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Dr. Hasyim Haddade, M.Ag.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Dr. Abdullah, M.Ag.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Dr. Muh. Thahir Maloko, M.HI.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Dr. H. Supardin, M.HI.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Dr. Shuhufi Abdullah, M.Ag.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Dr. Hamzah Hasan, M.HI.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Prof. Dr. H. Sattu Alang, M.A.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Dr. H. Supardin, M.Ag.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Drs. H. Mahyuddin Latuconsina, S.H., M.A.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Dr. Hamzah Hasan, M.H.I.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Dr. Musyfikah Ilyas, S.H.I., M.H.I.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Dr. Sitti Aisyah Chalik, M.Pd.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Dr. H. Rahman Ambo Masse, Lc., M.E.I.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Dr. Rahman Ambo Masse, M.E.I.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Prof. Dr. Hamzah Hasan, M.H.I.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Dr. Azman, M.Ag.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Dr. Besse Ruhaya, S.Pd.I., M.Pd.I.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Hastuti Baharuddin, S.Pd.I., M.Pd.I.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Dirhamzah, S.Pd.I., M.Pd.I.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Dr. Hj. Besse Ruhaya, S.Pd.I., M.Pd.I.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "A. Mustika Abidin, S.Pd.I., M.Pd.I.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Titi Mildawati, S.Pd.I., M.Pd.I.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Prof. Dr. Sohrah, M.Ag.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Muh. Sanusi Tinni, S.Kom.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Abdurrahman Ramli, S.Kom.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Rizky Gita Abadi, S.Kom.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Abdur Rahman Ramli, S.Kom.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Andi Tarmizi K. Rapi, S.Kom.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Rizky Gita Abadi, S.Kom., M.T.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Muh. Nur Pujianto, S.Kom.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Umar Muchtar",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
            [
                "name" => "Fathul Rahman Azis, S.Pt.",
                "gender" => null,
                "nip" => null,
                "signature" => null,
                "role" => "lecturer",
                "created_at" => Carbon::now(),
                "updated_at" => Carbon::now(),
            ],
        ];
        Lecturer::insert($lecturers);
    }
}
